### ISSUE TITLE
REMOTE_PIN_1 definition

### ISSUE THREAD

**Issue by johol** [jp112sdl/HB-UNI-SenAct-4-4#1]
Hello,
thank you very much for your work. May be following findings will be helpful.
The REMOTE_PIN_1 5 definition ist not working as expected.
After pressing the button the device is in a never ending loop
05 longpressed
<- 0B 17 86 40 CAFE07 000000 45 00  - 15538
05 longpressed
<- 0B 18 86 40 CAFE07 000000 45 00  - 15575
05 longpressed
....
I think pin 5 is used for battery monitoring
Changing to
#define REMOTE_PIN_1 3
do the trick.

Additionally I commented following line like in HB-UNI-SenAct-8-8
//      DPRINT("BATTERY IS LOW? "); DDECLN(this->device().battery().low());

Kind regards,
Jörg

**Comment by jp112sdl** [comment]
Hi!

That's very strange. I can't find out where Pin 5 is used somewhere else.
Battery measurement is done by internal reference, if `USE_BATTERY_MODE` is defined.
If not, there is no battery measurement at all.

Using Pin 3 is a good workaround for you. 
I will check the behaviour you observed in the next days _(I hope)_ ;)

**Comment by johol** [comment]
Hi,
sorry for the noise. It was my fault. I'm using this [https://github.com/alexreinert/PCB#hb-uni-sen-batt](url) pcb. There is pin 5 connected to a 2nd status led.

**Comment by jp112sdl** [comment]
Ah! :)
Thanks. 
No problem
