### ISSUE TITLE
Konfigurationsdaten stehen zur Übertragung an

### ISSUE THREAD

**Issue by yveszemp** [jp112sdl/HB-UNI-SenAct-4-4#2]
Hallo als erstes ein echter Lob für diese Arbeit und dass wir dies benutzen dürfen. Ich habe mir nun ein Modell nachgebaut, den SenAct 4-4. Jedoch wenn ich da Programme erstelle, erscheint unter den Servicemeldungen die Nachricht, dass Konfigurationsdaten zur übertragung anstehen, diese werde aber nie übertragen, und es funktioniert nur der erste Aktor, die anderen kann ich über ein Programm nicht ansteuern, nur wenn ich diese manuell im Geräte Bedienen Menu verwende. Was mache ich falsch ?
![55705055-2501d680-59de-11e9-9d34-1c3d6f225501](https://user-images.githubusercontent.com/49389039/55721564-f8f94c00-5a03-11e9-9bff-df6207fbd955.png)

Liegt es an der Device ID ? Ich habe da bei der ID das letzte bit als 0X02 gesetzt, sowie die ID auf JPSENACT02, ansonsten hätte ich einen zweiten auch nicht korrekt anlernen können.

Vielen Dank für ein Feedback.

**Comment by jp112sdl** [comment]
Hi,

> Ich habe da bei der ID das letzte bit als 0X02 gesetzt, sowie die ID auf JPSENACT02, ansonsten hätte 
ich einen zweiten auch nicht korrekt anlernen können.

da ich das von dir beschriebene Verhalten nicht nachstellen kann, vermute ich, dass du das 2. Gerät bereits versucht hattest, auch mit der `0x01` anzulernen?

Das Beste wäre, wenn du noch mal alle SenAct-4-4 ablernst, auf Werkseinstellung zurücksetzt und noch mal neu anlernt.

**Comment by yveszemp** [comment]
Hallo
Ja das ist so, ich habe ein Zweites Modul mit den selben Daten probiert anzumelden, ich werde dies machen, und alle Abmelden, und dann noch einmal neu anmelden, werde dann hier kommentieren, ob alles funktioniert hat. Vielen Dank für die schnelle Antwort.

**Comment by yveszemp** [comment]
Aktuell sieht es super aus, erste Tests waren nun erfolgreich. Vielen Dank für den Support.

**Comment by jp112sdl** [comment]
Freut mich! Danke für die Rückmeldung

**Comment by yveszemp** [comment]
Kann es sein, dass die Geräte über ein LAN Gateway nicht funktionieren ? Ich habe in meinem Büro, dort wo die CCU3 ist, alles in Betrieb genommen, die Programme erstellt und alles funktionierte super, danach habe ich das Modul an seinem Bestimmungsort montiert, da ist ein LAN Gateway, aber genau dann funktioniert das Modul nicht mehr. Wurde dies getestet, oder muss ich noch was anpassen.

**Comment by jp112sdl** [comment]
Habe ich nie getestet, da ich kein LAN Gateway besitze.
Versuchs mal mit drüberlernen.

CCU WebUI->Anlernmodus starten, anschließend Anlerntaster am SenAct-4-4 drücken.

Oder kann es sein, dass beim Zuordnen zum LAN Gateway noch mal Konfigurationsdaten übertragen werden?

Hab da keine Ahnung...

**Comment by yveszemp** [comment]
Es scheint ein Problem mit dem LAN Gateway zu sein. Ich habe nun zwar das Gerät wieder zum laufen gebracht, aber die Relais kann ich nun nicht mehr gebrauchen. Es kommen die Schaltbefehle an, aber man muss zum Teil auch mehrmals die Taster drücken bis der Befehl angenommen wird.
Ich werde mal schauen, dass ich Gateway und Zentrale von der Position tauschen kann, so dass ich dann das ganze testen kann.
